### ISSUE TITLE
What is the project? (or "please, add README")

### ISSUE THREAD

**Issue by Totktonada** [tarantool/easy-function#2]
I didn't know, how to start to look what is the project.

I asked @rosik. He said, I can download a deb package from CI artifacts or:

```
git clone
git submodule init
cartridge build
cartridge start
```

Then, AFAIU, I'll be prompted to open some URL in a web browser (didn't tried ATM).

**Comment by filonenko-mikhail** [comment]
Sorry, no plans for information support for this repo. Gently closing.
